USE Test2;
rollback
ALTER DATABASE Test SET ALLOW_SNAPSHOT_ISOLATION OFF;
--SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN TRANSACTION;
INSERT INTO liczby2 (liczba) VALUES (1);

UPDATE liczby1 SET liczba = 10;